apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - security.davano.io_artifactexceptions.yaml
  - security.davano.io_artifactscanpolicies.yaml
  - security.davano.io_artifactscanreports.yaml
  - security.davano.io_artifactscans.yaml
  - security.davano.io_complianceprofiles.yaml
  - security.davano.io_compliancereports.yaml
  - security.davano.io_modelregistryconnectors.yaml
  - security.davano.io_modelsecurityreports.yaml
  - security.davano.io_promotionrequests.yaml
  - security.davano.io_trustedpublishers.yaml
